In [2]:
import numpy as np


In [4]:
import tensorflow as tf

In [30]:
#lab2 part A
import tensorflow as tf
import tensorflow as tf
var_x=tf.constant([1.5,2.6,3.7,4.5],shape=[1,4],name='x')
var_y=tf.constant([5.8,6.6,7.0,8.0],shape=[1,4],name='y')
with tf.name_scope("mean"):
    with tf.name_scope("mean_x_y"):
        var_x1=tf.reduce_mean(var_x)
        var_y1=tf.reduce_mean(var_y)
        sess=tf.Session()
    print(sess.run(var_x1))
    print(sess.run(var_y1))
with tf.name_scope("variance"):
    with tf.name_scope("scope_sub1"):
        a=tf.subtract(var_x,var_x1)
        sess1=tf.Session()
    print(sess1.run(a))
    with tf.name_scope("scope_sub2"):
        b=tf.subtract(var_y,var_y1)
        sess2=tf.Session()
    print(sess2.run(b))
    with tf.name_scope("scope_square"):
        a1=tf.multiply(a,a)
        sess3=tf.Session()
    print(sess3.run(a1))
    with tf.name_scope("scope_summation"):
        var=tf.reduce_sum(a1)
        sess4=tf.Session()
    print(sess4.run(var))
with tf.name_scope("covariance"):
    with tf.name_scope("multiplication"):
        mul1=tf.multiply(a,b)
        sess5=tf.Session()
    print(sess5.run(mul1))
    with tf.name_scope("scope_summation2"):
        covar=tf.reduce_sum(mul1)
        sess6=tf.Session()
    print(sess6.run(covar))

3.075
6.85
[[-1.57499981 -0.4749999   0.62500024  1.42500019]]
[[-1.05000019 -0.25000048  0.14999962  1.14999962]]
[[ 2.48062444  0.2256249   0.3906253   2.03062558]]
5.1275
[[ 1.65375006  0.1187502   0.0937498   1.63874972]]
3.505


In [33]:
#lab1 assignment question 1
a=6
b=5


with tf.name_scope("lab1_assgn1"):
    with tf.name_scope("Scope_A"):
        var_x = tf.multiply(a, a)
        var_y = tf.multiply(b, b)
    with tf.name_scope("Scope_B"):
        z = tf.multiply(2, a)
        var_h = tf.multiply(z, b)

with tf.name_scope("Scope_C"):
    var_d = tf.add(var_x, var_y)
    var_s = tf.subtract(var_d, var_h)



with tf.Session() as sess:
    writer = tf.summary.FileWriter("/tmp/tboard/output22", sess.graph)
    print(sess.run(s))
    writer.close()

1


In [31]:
#lab 1 assignment2
variable1=tf.constant(3)
variable2=tf.constant(4)
with tf.name_scope("ADD"):
    variable3=tf.add(variable1,variable2)
    with tf.name_scope("multiply"):
        variable4=tf.multiply(variable1,variable1)
        variable5=tf.multiply(variable2,variable2)
        variable6=tf.multiply(variable1,variable2)
        with tf.name_scope("equation"):
            variable7=variable4+variable5-variable6
            variable8=tf.multiply(variable3,variable7)
sess=tf.Session()
writer = tf.summary.FileWriter("/tmp/tboard/output6", sess.graph)
print(sess.run(variable8))


91
